server:
  max-http-header-size: 8192
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
    threads:
      max: 400
  error:
    path: /error
spring:
  servlet:
    multipart:
      enabled: on
      max-file-size: 50MB
      max-request-size: 55MB
  redis:
    lettuce:
      pool:
        max-wait: 3000
        max-idle: 8
        min-idle: 1
    timeout: 3000
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/static/
#  mail:
#    host: smtpdm.aliyun.com
#    username: stackfarm@jitclass.cn
#    password: pe1FzURbv3h1bQiu
#    port: 80
#    protocol: smtp
#    default-encoding: UTF-8
#    test-connection: false
  mail:
    host: smtphz.qiye.163.com
    username: admin@jsdj.sportsjs.cn
    password: FurcQLmVWucTgfun
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false
  profiles:
    active: prod
    group:
      dev: "dev"
      prod: "prod"


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    org.springframework: WARN
# token过期时间，单位：小时
tokenExpireTime: 168
invCodeRemNum: 20

#手机短信发送
secretId: AKIDskMinCuJGxObZNO2tWKuCExSfjb0trBG
secretKey: 3rPgqlTv6KIk5A4nHZaKzLRGp8FSdkbE
appId: 1400504436
sender: 江苏省电子竞技运动协会
# 注册验证码模板
smsTemplateRegister: 917298
# 重置密码验证码模板
smsTemplateReset: 917302
# 报名成功通知模板
smsTemplateAccess: 920860

#邮箱用户名
emailUsername: admin@jsdj.sportsjs.cn
#emailUsername: stackfarm@jitclass.cn

#认证有效期 单位：年
authenticationEffectiveTime: 3
##年审开始时间(月-日) 用-分隔
#annualBeginTime: 12-31
##年审结束时间（月-日） 用-分隔
#annualEndTime: 1-31


